### ISSUE TITLE
Fails with yyplot

### ISSUE THREAD

**Issue by raacampbell** [raacampbell/shadedErrorBar#12]
See also #3 
```
Error using matlab.graphics.axis.Axes/set 
Children may only be set to a permutation of itself

Error in uistack (line 134) 
set(UParent,'Children',AllChildren);

Error in shadedErrorBar>makePlot (line 193) 
uistack(H.mainLine,'top') % Bring the main line to the top

Error in shadedErrorBar (line 126) 
H = makePlot(x,y,errBar,lineProps,transparent,patchSaturation);
```

**Comment by djsmith17** [comment]
I believe this has something to do with line 194:

uistack(H.mainLine,'top') % Bring the main line to the top

I commented out this line, and I was able to get this to work with yyaxis

**Comment by raacampbell** [comment]
IIRC, commenting out that line will cause the plot line to be hidden behind the shaded error region. I think it's also possible to perform the same operation by reordering the axis children (which are the plotted objects).

Can you send me the minimal example that generates the error?

**Comment by hollyhue** [comment]
Was this issue ever resolved? I would like to use plotyy with shaded error bars.

**Comment by raacampbell** [comment]
I haven't worked on it, no. Can you post a minimal example I can run that shows the problem?

**Comment by hollyhue** [comment]
Hello! Below is an example that gives the error (granted you do get a plot even with the error, but in my application I use "hold on" to plot multiple things on on axis, with this application it will only plot one variable then stop due to the error):

% given shadedErrorBar is present in current path
clc
clear all
close all

X1=[1:1:120];
Y11=randi([0 1],120,1);
Y12=randi([0 1],120,1);
Y13=randi([0 1],120,1);

Y1=[Y11,Y12,Y13];

avgY1=mean(Y1,2);
stdv1=std(Y1,0,2);

Y21=10^-6*randi([0 1],120,1);
Y22=10^-6*randi([0 1],120,1);
Y23=10^-6*randi([0 1],120,1);

Y2=[Y21,Y22,Y23];

avgY2=mean(Y2,2);
stdv2=std(Y2,0,2);
%%

figure(1)

yyaxis left
axis([0 120 -5 7])

shadedErrorBar(X1,avgY1,stdv1)

yyaxis right
axis([0 120 -5*10^-6 2*10^-6])

shadedErrorBar(X1,avgY2,stdv2)

**Comment by hollyhue** [comment]
It looks like someone has attempted to create a program that works with your program to resolve this issue -- but I cannot get it to work because I do not know what c1 and c2 are (same problem as person who commented on that program): https://www.mathworks.com/matlabcentral/fileexchange/42578-shaded-error-bar-yy

**Comment by raacampbell** [comment]
Ok. Thanks for the example code. I'll look into it.

**Comment by raacampbell** [comment]
This example is more brief:


```
figure(1), clf
y=rand(30,100);

yyaxis left
shadedErrorBar([],y,{@mean, @std})


yyaxis right
shadedErrorBar([],y+300,{@(x) mean(x), @(x) std(x)*1.96})
```

**Comment by raacampbell** [comment]
Or, more generally:
```
clf 
yyaxis left
p1=plot(rand(1,199));
yyaxis right
p2=plot(rand(1,199));
uistack(p1,'top') %Generates error
```

The error being:
```
>> uistack(p1,'top')
Error using matlab.graphics.axis.Axes/set
Children may only be set to a permutation of itself

Error in uistack (line 157)
            set(UParent,'Children',AllChildren);
```

**Comment by raacampbell** [comment]
@hollyhue can you please pull the latest version and see if it works for you?

**Comment by hollyhue** [comment]
@raacampbell sorry I never replied.... I still would like to get this to work. I still get the error with the latest version...

**Comment by hollyhue** [comment]
@raacampbell it works!!! Sorry for the 3 month delay in replying....oops.
